import { Role } from './types';

// Fix: Define constants used in the application.
export const ACCEPTED_IMAGE_TYPES = 'image/jpeg, image/png, image/webp';
export const ACCEPTED_DATA_TYPES = '.csv, .json, .xlsx, .xls';

export const LANGUAGES: { [key:string]: { [key: string]: string } } = {
  'en': {
    'dashboard': 'Dashboard',
    'tasks': 'Tasks',
    'land_health': 'Land Health',
    'plant_health': 'Plant Health',
    'dashboard_overview': 'Dashboard Overview',
    'soil_data_analysis': 'Dataset analyzer',
    'download_report': 'Download Report',
    'upload_soil_csv': 'Upload Dataset (.csv, .xlsx, .json)',
    'soil_analysis_result': 'Analysis Result',
    'yield_prediction': 'Predicted Yield',
    'profit_prediction': 'Predicted Profit',
    'summary_and_recommendations': 'Summary & Recommendations',
    'pending_tasks': 'Pending Tasks',
    'view_all_tasks': '... and more. Go to Tasks page to see all.',
    'weather_forecast': 'Weather Forecast',
    'humidity': 'Humidity',
    'wind': 'Wind',
    'weather_0': 'Clear sky',
    'weather_1': 'Mainly clear',
    'weather_2': 'Partly cloudy',
    'weather_3': 'Overcast',
    'weather_45': 'Fog',
    'weather_51': 'Drizzle',
    'weather_61': 'Rain',
    'weather_80': 'Rain showers',
    'day_0': 'Sun',
    'day_1': 'Mon',
    'day_2': 'Tue',
    'day_3': 'Wed',
    'day_4': 'Thu',
    'day_5': 'Fri',
    'day_6': 'Sat',
    'tasks_title': 'Task Manager',
    'new_task_placeholder': 'Add a new task...',
    'add': 'Add',
    'clear_completed': 'Clear All Completed Tasks',
    'chatbot_advisor': 'Farm Advisor',
    'ask_me': 'Ask me anything about your farm...',
    'listening': 'Listening...',
    'generate_image_prompt': "Try 'generate a picture of a futuristic tractor'",
    'upload_land_image': 'Upload Land Image',
    'land_health_map': 'Land Health Map',
    'healthy': 'Healthy',
    'medium_stress': 'Medium Stress',
    'high_stress': 'High Stress',
    'no_dataset_message': 'Upload an image to see the land health analysis.',
    'upload_plant_image': 'Upload Plant Image',
    'disease_detection_report': 'Disease Detection Report',
    'disease_name': 'Disease Name',
    'confidence': 'Confidence',
    'treatment_steps': 'Treatment Steps',
    'login_welcome': 'Welcome to AgroFarm',
    'name': 'Name',
    'email': 'Email',
    'password': 'Password',
    'mobile': 'Mobile Number',
    'role': 'Role',
    'select_role': 'Select your role',
    'role_farmer': Role.Farmer,
    'role_scientist': Role.Scientist,
    'role_researcher': Role.Researcher,
    'login': 'Login',
    'logout': 'Logout',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'language': 'Language',
  },
  'ta': { // Tamil
    'dashboard': 'டாஷ்போர்டு',
    'tasks': 'பணிகள்',
    'land_health': 'நில ஆரோக்கியம்',
    'plant_health': 'தாவர ஆரோக்கியம்',
    'dashboard_overview': 'டாஷ்போர்டு கண்ணோட்டம்',
    'soil_data_analysis': 'தரவுத்தொகுப்பு பகுப்பாய்வி',
    'download_report': 'அறிக்கையைப் பதிவிறக்குக',
    'upload_soil_csv': 'தரவுத்தொகுப்பைப் பதிவேற்றவும் (.csv, .xlsx, .json)',
    'soil_analysis_result': 'பகுப்பாய்வு முடிவு',
    'yield_prediction': 'கணிக்கப்பட்ட விளைச்சல்',
    'profit_prediction': 'கணிக்கப்பட்ட லாபம்',
    'summary_and_recommendations': 'சுருக்கம் & பரிந்துரைகள்',
    'pending_tasks': 'நிலுவையில் உள்ள பணிகள்',
    'view_all_tasks': '... மேலும். அனைத்தையும் காண பணிகள் பக்கத்திற்குச் செல்லவும்.',
    'weather_forecast': 'வானிலை முன்னறிவிப்பு',
    'humidity': 'ஈரப்பதம்',
    'wind': 'காற்று',
    'weather_0': 'தெளிவான வானம்',
    'weather_1': 'பெரும்பாலும் தெளிவாக',
    'weather_2': 'ஓரளவு மேகமூட்டம்',
    'weather_3': 'மேகமூட்டம்',
    'tasks_title': 'பணி மேலாளர்',
    'new_task_placeholder': 'புதிய பணியைச் சேர்க்கவும்...',
    'add': 'சேர்',
    'clear_completed': 'முடிந்த பணிகளை அழிக்கவும்',
    'chatbot_advisor': 'பண்ணை ஆலோசகர்',
    'ask_me': 'உங்கள் பண்ணை பற்றி என்னிடம் எதுவும் கேளுங்கள்...',
    'listening': 'கேட்கிறது...',
    'login_welcome': 'அக்ரோஃபார்மிற்கு வரவேற்கிறோம்',
    'name': 'பெயர்',
    'email': 'மின்னஞ்சல்',
    'password': 'கடவுச்சொல்',
    'mobile': 'கைபேசி எண்',
    'role': 'பங்கு',
    'select_role': 'உங்கள் பங்கைத் தேர்ந்தெடுக்கவும்',
    'role_farmer': 'விவசாயி/பயனர்',
    'role_scientist': 'பயிர் விஞ்ஞானி',
    'role_researcher': 'ஆராய்ச்சியாளர்',
    'login': 'உள்நுழை',
    'logout': 'வெளியேறு',
    'dark_mode': 'இருண்ட பயன்முறை',
    'light_mode': 'ஒளி பயன்முறை',
    'language': 'மொழி',
  },
  'fr': { // French
    'dashboard': 'Tableau de bord',
    'tasks': 'Tâches',
    'land_health': 'Santé des terres',
    'plant_health': 'Santé des plantes',
    'dashboard_overview': 'Aperçu du tableau de bord',
    'soil_data_analysis': 'Analyseur de jeu de données',
    'download_report': 'Télécharger le rapport',
    'upload_soil_csv': 'Télécharger le jeu de données (.csv, .xlsx, .json)',
    'soil_analysis_result': 'Résultat de l\'analyse',
    'yield_prediction': 'Rendement prévu',
    'profit_prediction': 'Bénéfice prévu',
    'summary_and_recommendations': 'Résumé et recommandations',
    'pending_tasks': 'Tâches en attente',
    'weather_forecast': 'Prévisions météo',
    'humidity': 'Humidité',
    'wind': 'Vent',
    'weather_0': 'Ciel clair',
    'weather_1': 'Généralement clair',
    'weather_2': 'Partiellement nuageux',
    'weather_3': 'Couvert',
    'tasks_title': 'Gestionnaire de tâches',
    'new_task_placeholder': 'Ajouter une nouvelle tâche...',
    'add': 'Ajouter',
    'clear_completed': 'Effacer les tâches terminées',
    'chatbot_advisor': 'Conseiller agricole',
    'ask_me': 'Posez-moi des questions sur votre ferme...',
    'listening': 'Écoute...',
    'login_welcome': 'Bienvenue chez AgroFarm',
    'name': 'Nom',
    'email': 'E-mail',
    'password': 'Mot de passe',
    'mobile': 'Numéro de portable',
    'role': 'Rôle',
    'select_role': 'Sélectionnez votre rôle',
    'role_farmer': 'Agriculteur/Utilisateur',
    'role_scientist': 'Phytologue',
    'role_researcher': 'Chercheur',
    'login': 'Connexion',
    'logout': 'Déconnexion',
    'dark_mode': 'Mode sombre',
    'light_mode': 'Mode clair',
    'language': 'Langue',
  },
  'ml': { // Malayalam
    'dashboard': 'ഡാഷ്ബോർഡ്',
    'tasks': 'ജോലികൾ',
    'land_health': 'ഭൂമിയുടെ ആരോഗ്യം',
    'plant_health': 'സസ്യങ്ങളുടെ ആരോഗ്യം',
    'dashboard_overview': 'ഡാഷ്ബോർഡ് അവലോകനം',
    'soil_data_analysis': 'ഡാറ്റാസെറ്റ് അനലൈസർ',
    'download_report': 'റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    'upload_soil_csv': 'ഡാറ്റാസെറ്റ് അപ്‌ലോഡ് ചെയ്യുക (.csv, .xlsx, .json)',
    'soil_analysis_result': 'വിശകലന ഫലം',
    'yield_prediction': 'പ്രതീക്ഷിത വിളവ്',
    'profit_prediction': 'പ്രതീക്ഷിത ലാഭം',
    'summary_and_recommendations': 'സംഗ്രഹവും ശുപാർശകളും',
    'pending_tasks': 'തീർച്ചപ്പെടുത്താത്ത ജോലികൾ',
    'weather_forecast': 'കാലാവസ്ഥാ പ്രവചനം',
    'humidity': 'ഈർപ്പം',
    'wind': 'കാറ്റ്',
    'weather_0': 'തെളിഞ്ഞ ആകാശം',
    'weather_1': 'പ്രധാനമായും തെളിഞ്ഞത്',
    'weather_2': ' ഭാഗികമായി മേഘാവൃതം',
    'weather_3': 'മേഘാവൃതം',
    'tasks_title': 'ടാസ്ക് മാനേജർ',
    'new_task_placeholder': 'ഒരു പുതിയ ടാസ്ക് ചേർക്കുക...',
    'add': 'ചേർക്കുക',
    'clear_completed': 'പൂർത്തിയായവ മായ്‌ക്കുക',
    'chatbot_advisor': 'ഫാം ഉപദേശകൻ',
    'ask_me': 'നിങ്ങളുടെ ഫാമിനെക്കുറിച്ച് എന്നോട് എന്തും ചോദിക്കൂ...',
    'listening': 'കേൾക്കുന്നു...',
    'login_welcome': 'അഗ്രോഫാമിലേക്ക് സ്വാഗതം',
    'name': 'പേര്',
    'email': 'ഇമെയിൽ',
    'password': 'പാസ്വേഡ്',
    'mobile': 'മൊബൈൽ നമ്പർ',
    'role': 'പങ്ക്',
    'select_role': 'നിങ്ങളുടെ പങ്ക് തിരഞ്ഞെടുക്കുക',
    'role_farmer': 'കർഷകൻ/ഉപയോക്താവ്',
    'role_scientist': 'വിള ശാസ്ത്രജ്ഞൻ',
    'role_researcher': 'ഗവേഷകൻ',
    'login': 'പ്രവേശിക്കുക',
    'logout': 'പുറത്തുകടക്കുക',
    'dark_mode': 'ഡാർക്ക് മോഡ്',
    'light_mode': 'ലൈറ്റ് മോഡ്',
    'language': 'ഭാഷ',
  },
  'te': { // Telugu
    'dashboard': 'డాష్బోర్డ్',
    'tasks': 'పనులు',
    'land_health': 'భూమి ఆరోగ్యం',
    'plant_health': 'మొక్కల ఆరోగ్యం',
    'dashboard_overview': 'డాష్బోర్డ్ అవలోకనం',
    'soil_data_analysis': 'డేటాసెట్ విశ్లేషణకారి',
    'download_report': 'నివేదికను డౌన్లోడ్ చేయండి',
    'upload_soil_csv': 'డేటాసెట్‌ను అప్‌లోడ్ చేయండి (.csv, .xlsx, .json)',
    'soil_analysis_result': 'విశ్లేషణ ఫలితం',
    'yield_prediction': 'అంచనా దిగుబడి',
    'profit_prediction': 'అంచనా లాభం',
    'summary_and_recommendations': 'సారాంశం & సిఫార్సులు',
    'pending_tasks': 'పెండింగ్ పనులు',
    'weather_forecast': 'వాతావరణ సూచన',
    'humidity': 'తేమ',
    'wind': 'గాలి',
    'weather_0': 'స్పష్టమైన ఆకాశం',
    'weather_1': 'ప్రధానంగా స్పష్టంగా ఉంది',
    'weather_2': 'పాక్షికంగా మేఘావృతం',
    'weather_3': 'మేఘావృతం',
    'tasks_title': 'టాస్క్ మేనేజర్',
    'new_task_placeholder': 'క్రొత్త పనిని జోడించండి...',
    'add': 'జోడించు',
    'clear_completed': 'పూర్తయినవి క్లియర్ చేయండి',
    'chatbot_advisor': 'వ్యవసాయ సలహాదారు',
    'ask_me': 'మీ పొలం గురించి నన్ను ఏదైనా అడగండి...',
    'listening': 'వినడం...',
    'login_welcome': 'ఆగ్రోఫామ్ కు స్వాగతం',
    'name': 'పేరు',
    'email': 'ఇమెయిల్',
    'password': 'పాస్వర్డ్',
    'mobile': 'మొబైల్ నంబర్',
    'role': 'పాత్ర',
    'select_role': 'మీ పాత్రను ఎంచుకోండి',
    'role_farmer': 'రైతు/వినియోగదారు',
    'role_scientist': 'పంట శాస్త్రవేత్త',
    'role_researcher': 'పరిశోధకుడు',
    'login': 'ప్రవేశించండి',
    'logout': 'లాగ్ అవుట్',
    'dark_mode': 'డార్క్ మోడ్',
    'light_mode': 'లైట్ మోడ్',
    'language': 'భాష',
  },
   'kn': { // Kannada
    'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'tasks': 'ಕಾರ್ಯಗಳು',
    'land_health': 'ಭೂಮಿ ಆರೋಗ್ಯ',
    'plant_health': 'ಸಸ್ಯ ಆರೋಗ್ಯ',
    'dashboard_overview': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್ ಅವಲೋಕನ',
    'soil_data_analysis': 'ಡೇಟಾಸೆಟ್ ವಿಶ್ಲೇಷಕ',
    'download_report': 'ವರದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    'upload_soil_csv': 'ಡೇಟಾಸೆಟ್ ಅಪ್ಲೋಡ್ ಮಾಡಿ (.csv, .xlsx, .json)',
    'soil_analysis_result': 'ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶ',
    'yield_prediction': 'ಊಹಿಸಲಾದ ಇಳುವರಿ',
    'profit_prediction': 'ಊಹಿಸಲಾದ ಲಾಭ',
    'summary_and_recommendations': 'ಸಾರಾಂಶ ಮತ್ತು ಶಿಫಾರಸುಗಳು',
    'pending_tasks': 'ಬಾಕಿ ಉಳಿದಿರುವ ಕಾರ್ಯಗಳು',
    'weather_forecast': 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
    'humidity': 'ಆರ್ದ್ರತೆ',
    'wind': 'ಗಾಳಿ',
    'weather_0': 'ಸ್ಪಷ್ಟ ಆಕಾಶ',
    'weather_1': 'ಮುಖ್ಯವಾಗಿ ಸ್ಪಷ್ಟವಾಗಿದೆ',
    'weather_2': 'ಭಾಗಶಃ ಮೋಡ ಕವಿದಿದೆ',
    'weather_3': 'ಮೋಡ ಕವಿದಿದೆ',
    'tasks_title': 'ಕಾರ್ಯ ನಿರ್ವಾಹಕ',
    'new_task_placeholder': 'ಹೊಸ ಕಾರ್ಯವನ್ನು ಸೇರಿಸಿ...',
    'add': 'ಸೇರಿಸಿ',
    'clear_completed': 'ಪೂರ್ಣಗೊಂಡವನ್ನು ತೆರವುಗೊಳಿಸಿ',
    'chatbot_advisor': 'ಕೃಷಿ ಸಲಹೆಗಾರ',
    'ask_me': 'ನಿಮ್ಮ ತೋಟದ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನು ಬೇಕಾದರೂ ಕೇಳಿ...',
    'listening': 'ಕೇಳುತ್ತಿದೆ...',
    'login_welcome': 'ಆಗ್ರೋಫಾರ್ಮ್‌ಗೆ ಸುಸ್ವಾಗತ',
    'name': 'ಹೆಸರು',
    'email': 'ಇಮೇಲ್',
    'password': 'ಗುಪ್ತಪದ',
    'mobile': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    'role': 'ಪಾತ್ರ',
    'select_role': 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'role_farmer': 'ರೈತ/ಬಳಕೆದಾರ',
    'role_scientist': 'ಬೆಳೆ ವಿಜ್ಞಾನಿ',
    'role_researcher': 'ಸಂಶೋಧಕ',
    'login': 'ಲಾಗಿನ್ ಮಾಡಿ',
    'logout': 'ಲಾಗ್ ಔಟ್',
    'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    'light_mode': 'ಲೈಟ್ ಮೋಡ್',
    'language': 'ಭಾಷೆ',
  }
};